[project]
name = "agent-service"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "root", email = "2139620064@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
agent-service = "agent_service:main"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
