[project]
name = "agent-service"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "root", email = "2139620064@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "uvicorn>=0.54.0",
    "pydantic",
    "pydantic-settings",
    "langchain>=1.4.3",
    "langchain-openai>=1.6.7",
    "langchain-tavily>=0.2.18",
    "langgraph>=1.2.13",
    "langgraph-checkpoint-redis>=0.5.2",
    "langchain-mcp-adapters",
    "mcp-server-time",
    "httpx",
    "mineru>=4.0,<5",
    "langchain-text-splitters",
    "langchain-huggingface",
    "sentence-transformers",
    "langchain-milvus",
    "pymilvus"
]

[project.scripts]
agent-service = "app.main:main"

[[tool.uv.index]]
url = "https://pypi.org/simple/"
default = true

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
